### PR TITLE
Access `inst/app/www` files 

### LINKED ISSUE #166: can't load ADaM dataset: "Warning: Error in file: cannot open the connection"
Hello,
I have just discovered tidyCDISC package and had fun playing with it.

I did a local instal and was able to play around with pilot data without any fuzz.

While loading datasets, I have one file that did not load.

The error on the console was:
`Warning in file(con, "rb") :
  cannot open file 'inst/app/www/red_x.png': No such file or directory
Warning: Error in file: cannot open the connection`

I tried to load the file in R, re-export it to make sure that the file itself was not corrupted but without any impact.
Any ideas on the troubleshooting steps?

Bests,

NB: Below sessionInfo(output)

`R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] haven_2.5.1     shiny_1.7.4     tidyCDISC_0.2.0 devtools_2.4.5  usethis_2.1.6  

loaded via a namespace (and not attached):
  [1] fs_1.6.1           fontawesome_0.5.0  insight_0.19.0     RColorBrewer_1.1-3 httr_1.4.4         rprojroot_2.0.3    tippy_0.1.0        tools_4.2.0        profvis_0.3.7     
 [10] bslib_0.4.2        DT_0.27            utf8_1.2.3         R6_2.5.1           sjlabelled_1.2.0   lazyeval_0.2.2     colorspace_2.1-0   urlchecker_1.0.1   withr_2.5.0       
 [19] tidyselect_1.2.0   prettyunits_1.1.1  GGally_2.1.2       processx_3.8.0     curl_5.0.0         compiler_4.2.0     cli_3.6.0          gt_0.8.0           xml2_1.3.3        
 [28] shinyjs_2.1.0      desc_1.4.2         plotly_4.10.1      sass_0.4.5         scales_1.2.1       readr_2.1.4        callr_3.7.3        stringr_1.5.0      digest_0.6.31     
 [37] rmarkdown_2.20     pkgconfig_2.0.3    htmltools_0.5.4    sessioninfo_1.2.2  attempt_0.3.1      fastmap_1.1.0      htmlwidgets_1.6.1  rlang_1.0.6        rstudioapi_0.14   
 [46] jquerylib_0.1.4    generics_0.1.3     jsonlite_1.8.4     crosstalk_1.2.0    dplyr_1.1.0        config_0.3.1       magrittr_2.0.3     Matrix_1.5-3       Rcpp_1.0.10       
 [55] munsell_0.5.0      fansi_1.0.4        lifecycle_1.0.3    stringi_1.7.12     IDEAFilter_0.1.2   yaml_2.3.7         pkgbuild_1.4.0     plyr_1.8.8         shinyTime_1.0.3   
 [64] grid_4.2.0         promises_1.2.0.1   forcats_1.0.0      crayon_1.5.2       lattice_0.20-45    miniUI_0.1.1.1     splines_4.2.0      hms_1.1.2          knitr_1.42        
 [73] ps_1.7.2           pillar_1.8.1       pkgload_1.3.2      glue_1.6.2         cicerone_1.0.4     evaluate_0.20      golem_0.3.5        data.table_1.14.8  remotes_2.4.2     
 [82] tzdb_0.3.0         vctrs_0.5.2        httpuv_1.6.9       gtable_0.3.1       purrr_1.0.1        tidyr_1.3.0        reshape_0.8.9      assertthat_0.2.1   cachem_1.0.6      
 [91] ggplot2_3.4.1      xfun_0.37          mime_0.12          xtable_1.8-4       roxygen2_7.2.3     later_1.3.0        ggcorrplot_0.1.4   survival_3.5-3     viridisLite_0.4.1 
[100] tibble_3.1.8       memoise_2.0.1      shinyWidgets_0.7.6 ellipsis_0.3.2     timevis_2.1.0     `

### PR DESCRIPTION
**Pull request by AARON-CLARK**
Fixes #166  bug by using `system.file()` to access these files. Besides the issues with the `red_x.png` mentioned on #166, I also found an issue downloading reports on the Individual explorer tab (below). The first download was using the old method, and the second attempt was using system.file(). 

image

Note that the "old method" will work inside the `tidyCDISC` project, so if you're going to test, I recommend running the following in a fresh R session:

```
remotes::install_github("Biogen-Inc/tidyCDISC", ref = "ac-166-access-png") # May Require Rtools
packageVersion("tidyCDISC") # should be v0.2.0.90001
tidyCDISC::run_app()
```

### CODE REVIEW

**Review by Jeff-Thompson12 — COMMENTED** [review]
@AARON-CLARK in the "app_config.R" file, {golem} has created a wrapper for `system.file()` with the package argument pre-specified.

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK in the "app_config.R" file, {golem} has created a wrapper for `system.file()` with the package argument pre-specified.

Ah, true.

**Comment by tdwils** [comment]
@AARON-CLARK  I followed your instructions above and ran the app in a new session. I was able to select datasets with missing variables, and the red X displayed correctly.

I was able to download an html file from the Individual Explorer, but attempting to save as PDF gave an error:

image

```
Warning in system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
  '"pdflatex"' not found
Warning: Error in : LaTeX failed to compile C:\Users\twilson4\AppData\Local\Temp\RtmpIz29Ua\file3e4077ba89f.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>
```

I also got a message when I first started the app:

```
The `name` provided ('chevron-down w3-tiny') does not correspond to a known icon
```

**Comment by AARON-CLARK** [comment]
> I was able to download an html file from the Individual Explorer, but attempting to save as PDF gave an error:

Hmmm, I think you just need to follow the instructions given in the error message. See https://yihui.org/tinytex/r/#debugging to update `tinytex`

> I also got a message when I first started the app: `The 'name' provided ('chevron-down w3-tiny') does not correspond to a known icon`

That is strange. I got that message too. I'm not really sure why it's showing up on my branch, but not `devel` or `master`...

**Review by tdwils — APPROVED** [review]
The download works. Looks good to me!

**Pull request merged**
