### PR TITLE
Use "ALL" with recipes

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Meant to address #135

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
The PR is currently marked as "draft" until #138 is merged into `devel`

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
I know this is still marked as draft, but I just checked it out and noticed that the 'baseline' visit is missing for each variable/param. Each one starts at week 2:

image

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK I actually fixed this with commit cc561a213ac61c8c6eb9b978c6c28fd7ff2902d2. The changes were done in a JS file which requires the R session to be reset. Can you try resetting your session?

**Review by AARON-CLARK — APPROVED** [review]
You're right @Jeff-Thompson12! Looks good to me after a restart.

**Pull request merged**
