### PR TITLE
CRAN: `Get Started with tidyCDISC` vignette

### PR DESCRIPTION
**Pull request by AARON-CLARK**
Switched all GIFs to PNGs to reduce file size, so there is at least one vignette on file.

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, I've been struggling to get this branch to pass `R CMD Check` and `pkgdown` github action checks. Do you think you could take a look at it? I've been pulled away to other projects off an on lately, making it difficult to dig into the root issue.

**Comment by Jeff-Thompson12** [comment]
Sure. I can take a look. I've been working on other projects as well but will have time tomorrow.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK did you still want me to take a look? I noticed that you have it passing the checks now.

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK did you still want me to take a look? I noticed that you have it passing the checks now.

I tried some stuff out an it worked! Let me clean up the repo a little bit and I'll have you review the PR for merge into `for_cranny`

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, once the checks are complete, this PR should be all ready for your review! Thanks

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, you are 100% right about that blog announcement. Please fix up the `cran_vignette` branch as you see fit and we'll get this puppy submitted to CRAN next week!

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK, another item we should consider is creating a CRAN announcement article. Otherwise, what is the point of the Blog section.

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK, another item we should consider is creating a CRAN announcement article. Otherwise, what is the point of the Blog section.

Yes, @Jeff-Thompson12, good idea. We can do that any time after the package get's accepted/ published.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK, I made some changes. Let me know what you think.

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, LGTM!

**Pull request merged**
