### PR TITLE
Fix PopEx Filter

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Only let filters be selected based on the selected data frames.

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
Addresses #48

**Comment by AARON-CLARK** [comment]
Hi @Jeff-Thompson12, friendly reminder to post a screenshot of the proposed solution just to make reviewing code a little easier. Is this what you got?

image

It looks like the solution makes sure there are no values to select for `AEACN`, which is an improvement. BUT not allowing the user to even select that variable would be even better. I think [dgkf/shinyDataFilter](https://github.com/dgkf/shinyDataFilter) created a way for developers to give users only select columns to filter, but keep those column in the returned data.frame. Check out PR 16... but that would mean copying his work into `{IDEAFilter}` which would be a pain. Do you have another idea perhaps?

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK This PR is ready for a fresh look.

**Review by AARON-CLARK — APPROVED** [review]
This appears to be working as expected! Amazing @Jeff-Thompson12!

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
Oh, forgot to ask if you could please increment the dev version & update the `NEWS.md` file? Then it's ready to merge!

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, whoops. I just merged #139 without requesting a bullet point in the `NEWS.md` file. It'd be okay with me if you could just add it to this PR. Thanks!

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK news and version have been updated.

**Review by AARON-CLARK — APPROVED** [review]

**Pull request merged**
