### PR TITLE
Make long facet & legend variables more readable

### LINKED ISSUE #200: Facet labels should be multi-line
This may be for a future enhancement:

If you create a facetted plot, separated e.g. by ACTARM, and the values for ACTARM are very long, the title of each facetted plot extends beyond the plot and is unreadable. Need to wrap the titles of the facetted plots. I have a screenshot with an example.

The same thing happens with boxplots with long x labels: they overlap and are unreadable.

_Originally posted by @tdwils in https://github.com/Biogen-Inc/tidyCDISC/issues/172#issuecomment-1458885750_

### PR DESCRIPTION
**Pull request by AARON-CLARK**
This PR which impacts both the scatterplot and line plot modules and closes #200. See issue for more details!

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
Hi @tdwils, this PR is ready for another review. The issue was that the `ggplot2` object looked beautiful, but a lot of configurations aren't supported or come out looking quite different when passed through `plotly::ggplotly()` so I had to make some overall `plotly::layout()` changes to correct the issue. Let me know how things look on your end!

**Review by tdwils — CHANGES_REQUESTED** [review]
Hi @AARON-CLARK , the legend is looking good, but I am still getting overlap with a long title:

image


I tried adding a top margin to the layout like [here](https://stackoverflow.com/questions/42821171/fix-plotly-ggplotly-title-overlapping-plot-when-title-is-split-on-two-lines?noredirect=1&lq=1 )  and that was a little better. I think ideally, the height of the space where the title is located would be a function of the title length.

**Comment by AARON-CLARK** [comment]
Hi @tdwils, can you please test one more time given my new commits? Before pursuing a `plotly` margin solution that is a function of other variables, I think / hope the new fix will work for you. 🤞🏼

**Review by tdwils — APPROVED** [review]
That did it. Looks good!

**Pull request merged**
