### PR TITLE
Update Demo

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
Addresses #119

**Comment by AARON-CLARK** [comment]
closes #119

**Comment by AARON-CLARK** [comment]
Hey Jeff,

This looks good to me. However, what do you think about merging the `devel` into `master` and then incorporating [those recent changes](https://github.com/Biogen-Inc/tidyCDISC/pull/123) (detailed in the image below) into the `demo` branch too? I think a lot of them are really useful and clean up some things. At this point, I have the attitude of, "we might as well, right?"

image

**Comment by Jeff-Thompson12** [comment]
Yes, that's probably a good idea. I will make a PR to merge `devel`.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK The new `master` has been merged. Go ahead and take a look.

**Comment by AARON-CLARK** [comment]
Test deployment of `update_demo` branch looks good: https://rinpharma.shinyapps.io/tidyCDISC_test/

Merging!

**Comment by AARON-CLARK** [comment]
https://rinpharma.shinyapps.io/tidyCDISC/ is now deployed based on the `demo` branch.

**Pull request merged**
