### PR TITLE
Development branch merge

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Update `master` with developments

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK Looks like at least NEWS.md needs to be updated before we merge. Can you think of anything else?

Yes, please increment with `usethis::use_version("patch")` to bump up the version number and update NEWS.md. For completeness, here's those feature enhancements you worked on:

image

After that, just give it a test to make sure it all works one last time.

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK I just noticed that we are exporting new functions with `devel` that are not available in the CRAN release. Do we want to add something to the R script to check the user's version of tidyCDISC?

@Jeff-Thompson12, oh shoot. You're right. That would be increase the convenience factor for the user. Something that installed the latest version from github using `remotes::install_github('Biogen-Inc/tidyCDISC')`?

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, you probably saw this too, but just want to make sure. Thank goodness for running `{pkgdown}` workflows on PRs, right? haha

image

**Comment by Jeff-Thompson12** [comment]
> @Jeff-Thompson12, oh shoot. You're right. That would be increase the convenience factor for the user. Something that installed the latest version from github using `remotes::install_github('Biogen-Inc/tidyCDISC')`?

We could do that. I was thinking about in general application development too. It might be helpful to hard code what version of the application the R Script was built using. That was the user can verify if they are using the correct one. But that's more of a "super" user designation. Your recommendation is probably the right approach.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK I also noticed a bug while working on the R script where the STAN table doesn't automatically populate on the first selection. I will try to fix that today as well.

image

**Comment by Jeff-Thompson12** [comment]
Evidently the STAN tables don't populate only when using the Viewer in RStudio ¯\_(ツ)_/¯. Does not appear to be a problem in a web browser.

@AARON-CLARK I don't know if this is actually a problem or not. Anyways, this PR is ready for you to take another look.

**Pull request merged**
