### PR TITLE
Function to help create `blockData` object

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
This PR seeks to create a sensible way for a user to create the `blockData` object which is passed to `tg_gt()`. See also, #126.

There are a handful of items that would need to be addressed for implementation:

- [x] Create functions to do data manipulation in both the shiny app and R6 class (to remove copied code).
- [x] Create wrappers for the R6 functions for easier implementation by users.
- [x] Create an export of the `blockData` object in the R6 class
- [x] Allow removal of blocks
- [x] Add "title" and "group_by" functionality
- [x] Export JSON of block for "recipe"
- ~~Incorporate usage into R script export~~

To test run the current code you can run the following:
```
devtools::load_all()
datalist <- list(ADSL = tidyCDISC::adsl, ADVS = tidyCDISC::advs, ADAE = tidyCDISC::adae, ADLBC = tidyCDISC::adlbc)
blockData <- table_blocks$new(datalist)
blockData$add_block()

#The values can also be passed into the function
blockData$add_block("DIABP", "MEAN", "ALL")
```

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
Wrappers have been added. Below is a demonstration of creating the block data for the demography table compared with the current R script generated by the package.
```
datalist <- list(ADSL = tidyCDISC::adsl, ADVS = tidyCDISC::advs, ADAE = tidyCDISC::adae, ADLBC = tidyCDISC::adlbc)

blockData <- structure(list(agg = c("FREQ", "MEAN", "FREQ", "FREQ", "FREQ", "MEAN", "MEAN"),
                            block = c("AGEGR1", "AGE", "SEX", "ETHNIC", "RACE", "HEIGHTBL", "WEIGHTBL"),
                            dataset = c("ADSL", "ADSL", "ADSL", "ADSL", "ADSL", "ADSL", "ADSL"),
                            dropdown = c(NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, NA_character_),
                            S3 = list(structure("AGEGR1", class = c("character", "ADSL")),
                                      structure("AGE", class = c("character", "ADSL")),
                                      structure("SEX", class = c("character", "ADSL")),
                                      structure("ETHNIC", class = c("character", "ADSL")),
                                      structure("RACE", class = c("character", "ADSL")),
                                      structure("HEIGHTBL", class = c("character", "ADSL")),
                                      structure("WEIGHTBL", class = c("character", "ADSL" ))),
                            gt_group = structure(c("FREQ of AGEGR1", "MEAN of AGE", "FREQ of SEX", "FREQ of ETHNIC", "FREQ of RACE", "MEAN of HEIGHTBL", "MEAN of WEIGHTBL"),
                                                 class = c("glue", "character")),
                            label = c("Pooled Age Group 1", "Age", "Sex", "Ethnicity", "Race", "Baseline Height (cm)", "Baseline Weight (kg)"),
                            label_source = c("SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute")),
                       row.names = c(NA, -7L),
                       class = c("tbl_df", "tbl", "data.frame"))

bd <- createBlockdata(datalist)
bd |>
  addBlock("AGEGR1", "FREQ") |>
  addBlock("AGE", "MEAN") |>
  addBlock("SEX", "FREQ") |>
  addBlock("ETHNIC", "FREQ") |>
  addBlock("RACE", "FREQ") |>
  addBlock("HEIGHTBL", "MEAN") |>
  addBlock("WEIGHTBL", "MEAN")
```

**Comment by Jeff-Thompson12** [comment]
Merging #235 so that functionality can be tested on writing the JSON export file.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK I'm thinking about leaving the last item "Incorporate usage into R script export" for another PR unless you think differently. I need to incorporate the new S3 methods into the R script as well anyways.

This PR has gotten a little massive and out of control so I think I need to be wrapping it up.

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, sounds good! I'll take a look at #235

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, #235 is merged into `devel`. Apologies that it took so long.

**Comment by Jeff-Thompson12** [comment]
> @Jeff-Thompson12, #235 is merged into `devel` so that this PR can come out of draft mode. Apologies that it took so long.

It's okay. I feel a little bad with how many PRs I've been dumping on you lately. When do you have time to do your own work?

**Comment by AARON-CLARK** [comment]
> Wrappers have been added. Below is a demonstration of creating the block data for the demography table compared with the current R script generated by the package.
> 
> ```
> devtools::load_all()
> datalist <- list(ADSL = tidyCDISC::adsl, ADVS = tidyCDISC::advs, ADAE = tidyCDISC::adae, ADLBC = tidyCDISC::adlbc)
> 
> blockData <- structure(list(agg = c("FREQ", "MEAN", "FREQ", "FREQ", "FREQ", "MEAN", "MEAN"),
>                             block = c("AGEGR1", "AGE", "SEX", "ETHNIC", "RACE", "HEIGHTBL", "WEIGHTBL"),
>                             dataset = c("ADSL", "ADSL", "ADSL", "ADSL", "ADSL", "ADSL", "ADSL"),
>                             dropdown = c(NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, NA_character_),
>                             S3 = list(structure("AGEGR1", class = c("character", "ADSL")),
>                                       structure("AGE", class = c("character", "ADSL")),
>                                       structure("SEX", class = c("character", "ADSL")),
>                                       structure("ETHNIC", class = c("character", "ADSL")),
>                                       structure("RACE", class = c("character", "ADSL")),
>                                       structure("HEIGHTBL", class = c("character", "ADSL")),
>                                       structure("WEIGHTBL", class = c("character", "ADSL" ))),
>                             gt_group = structure(c("FREQ of AGEGR1", "MEAN of AGE", "FREQ of SEX", "FREQ of ETHNIC", "FREQ of RACE", "MEAN of HEIGHTBL", "MEAN of WEIGHTBL"),
>                                                  class = c("glue", "character")),
>                             label = c("Pooled Age Group 1", "Age", "Sex", "Ethnicity", "Race", "Baseline Height (cm)", "Baseline Weight (kg)"),
>                             label_source = c("SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute", "SAS \"label\" attribute")),
>                        row.names = c(NA, -7L),
>                        class = c("tbl_df", "tbl", "data.frame"))
> blockData
> 
> bd <- createBlockdata(datalist)
> bd |>
>   addBlock("AGEGR1", "FREQ") |>
>   addBlock("AGE", "MEAN", "NONE") |>
>   addBlock("SEX", "FREQ") |>
>   addBlock("ETHNIC", "FREQ") |>
>   addBlock("RACE", "FREQ") |>
>   addBlock("HEIGHTBL", "MEAN", "NONE") |>
>   addBlock("WEIGHTBL", "MEAN", "NONE")
> bd
> ```

🥇 
@Jeff-Thompson12, this looks amazing! The ugliness of how the `blockData` object was formed in our downloadable R scripts is a major barrier to entry. Yeah, we generate it for users automatically, but it just looks overly complicated and made it difficult if users wanted to customize their tables outside of the app later. Plus it creates an illusion that `tidyCDISC` code is messy or had a certain stench to it. The simplicity of the proposed solution looks very elegant and will certainly encourage users to give it a try.

Here are some of my initial thoughts:



## Differing outputs
My first question is why the two outputs differ (R6 vs R Downloader)? Below, the new R6 process has a few values for the `dropdown` field that state "NONE". It appears to just show up for the quantitative vars. I assume this is an improvement since quantitative vars can't have dropdowns? In addition, is the new R6 process not able to gather labels from the data? 

image




## Variable's Source is not explicit
Second, the syntax is beautiful, but how does the `addBlock()` function know where to source each variable from? For example, what if "SEX" existed in both `ADSL` and `ADAE` when building an AE table? I made up a fictitious example below. It looks like the function defaults to using the `ADSL` as the source, but why? Is that always the case? What if there are similar variable between an `ADAE` and an `ADLB` that don't exist in the ADSL? Which source would it choose then? What if the user wanted to use a different source than the "default" behavior? I'm not sure I have use cases to back up these scenarios, but I thought I'd raise the concern now.

image



## Consistency between `removeBlock()` syntax and `addBlock()` syntax?

Without playing too much attention to the documentation, I thought I could remove a block using the same `addBlock()` syntax:
```r
bd_ae |> removeBlock("SEX", "FREQ") 
```
However, I realized I needed to provide the row number to remove. I wonder if we could create more consistency between how blocks are added and removed? Although, I see we'd get in trouble when there are more than 1 row containing "SEX/ FREQ" blocks in the table... Maybe we just delete the first row that matches that description by default? Or I like the idea of removing all the rows containing that block design. What do you think? Just an idea.



## Insert block into desired row

From a usage stand point, it might be nice to provide an option for the user to insert a new block in a location of their choosing? For example, if I'm working with a Table 41, which contains a lot of blocks, instead of having to recreate the block object from scratch in the desired order, what if users could leave the `blockData` object alone, but "drop" a new block into the first row? That way, they could leave the `tidyCDISC` generated code alone, which I think most people would prefer to do. The new proposed argument would be optional and could be called `row_position` or something similar?

image


## `setGroup()` error

Am I using this exported function wrong?

image

## `setTitle()` error

Am I using this exported function wrong?

image

**Review by AARON-CLARK — COMMENTED** [review]
Another comment:

**Comment by Jeff-Thompson12** [comment]
## Differing outputs
So this is a longer conversion that probably would be better to have elsewhere than this PR. The `blockData` object was from the recipe for that table. If you try to recreate that table and load ADSL and ADAE, you will get the same behavior as `addBlock()`. Also, if you only load ADSL, you will have missing values instead of "NONE".

I had not gather labels since it was only used for SAS comparison, but I can look into adding it. I don't think it will be a problem.

## Variable's Source is not explicit
That is undesirable behavior. The function was supposed to check if there was more than one possible data source, and ask the user to specify.

## Consistency between `removeBlock()` syntax and `addBlock()` syntax?
Maybe doing something inbetween would be good. Maybe we can mimic `dplyr::filter()` behavior.

## Insert block into desired row
I was contemplating with a redesign of `addBlock()` to incorporate more growth. This was one reason I was thinking about a slight redesign. I will work on incorporating this ability.

## `setGroup()` error
Yes, you are using it correctly. Somehow things got turned around between `setGroup()` and `setTitle()`.

## `setTitle()` error
Yes, you are using it correctly. Somehow things got turned around between `setGroup()` and `setTitle()`.

**Comment by Jeff-Thompson12** [comment]
There is something different between how the environment for `test-coverage` and `pkgdown` is being setup from `R-CMD-check` that is causing them to fail right now. It shouldn't be related to this PR. I have not messed with `renv` at all.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK I don't know why the tests are failing. They don't seem to be related to any changes that I have made. This is ready for you to take another look.

**Comment by Jeff-Thompson12** [comment]
I have opened a separate PR to deal with the Github Actions

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
@Jeff-Thompson12, sorry this took me like a week to get to (again). Looks great! I have a few comments:

(1) `setGroup()` and `setTitle()` don't error now. Yay! However, I am a R6 newb, so can you tell me how to extract those values out of the object I created below? I think it would be nice to add that to the documentation for each of those functions, maybe in the `@details` section?



(2) It looks like labels aren't being pulled in. I think those would be useful to include.

That's all for now! Thanks!

**Comment by Jeff-Thompson12** [comment]
> (1) `setGroup()` and `setTitle()` don't error now. Yay! However, I am a R6 newb, so can you tell me how to extract those values out of the object I created below? I think it would be nice to add that to the documentation for each of those functions, maybe in the `@details` section?

@AARON-CLARK so the display of the object is actually custom:
```
print = function() {
  print(self$blocks)
  invisible(self)
}
```
This could be solved in one of two ways. I can either highlight that title can be set/seen by looking at `bd_ae$title`, or I can adjust the print statement to print not just the blocks but the title and grouping variable as well. Thoughts?

**Comment by AARON-CLARK** [comment]
> This could be solved in one of two ways. I can either highlight that title can be set/seen by looking at `bd_ae$title`, or I can adjust the print statement to print not just the blocks but the title and grouping variable as well. Thoughts?

Why not both? I like the idea of both.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK The labels are not created in the exact same way as is being currently handled in `tableGen`, but it should still be providing the expected behavior.

**Review by AARON-CLARK — APPROVED** [review]
It's beautiful... 😭 

image

**Pull request merged**
