### PR TITLE
Fix STAN table error(s) & R Script from loading all CDISC pilot data

### LINKED ISSUE #104: Standard Tables Broken
Some of the standard tables appear to be broken now.

image

image

### LINKED ISSUE #108: Downloadable R script includes all CDISC data, regardless of data sets chosen.

### PR DESCRIPTION
**Pull request by AARON-CLARK**
This PR fixes #104. Please test! I'm not sure why, but I found that the code was running `varN_fctr_reorder()` more than once on the ADAE dataset, so I just removed it. I also found redundant use on the BDS dataset, so I removed that too.

PR also fixes #108, as seen here:
image

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
So essentially the fix amounts to removing the two redundant uses of `varN_fctr_reorder()`. Why was the original iteration of the function using `forcats` not breaking those STAN tables?

**Review by Jeff-Thompson12 — APPROVED** [review]
Everything looks good to me.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Are you done working on this PR? 'Asking because you pushed a handful of commits after asking for my review.

**Comment by AARON-CLARK** [comment]
> Why was the original iteration of the function using `forcats` not breaking those STAN tables?

@Jeff-Thompson12. That is a great question. I recall the "OG" `varN_fctr_reorder()` was kind of a black box to me because I didn't spend much time to grasp it. Why not? Well, (1) because I lacked `data.table` pkg experience and (2) because we needed to lighten our dependency load for CRAN submission. The the "new" `varN_fctr_reorder()` was supposed to be simpler, which is why it relies on the base R `factor()` function for re-leveling. However, the way the function is written, it drops levels that don't exist in the data anymore. So, when those data frames are filtered using the `semi_join()` [here](https://github.com/Biogen-Inc/tidyCDISC/blob/8ce64ddd1024da0cd0582f5eb9472967d664a444/R/mod_tableGen.R#L702), they lose a factor level, which is why `setNames()` throw the error [here](https://github.com/Biogen-Inc/tidyCDISC/blob/8ce64ddd1024da0cd0582f5eb9472967d664a444/R/mod_tableGen.R#L497). I did some lite testing, and with or without the redundant `varN_fctr_reorder()`, the `common_rownames()` part always returned the same values, but but I found out the underlying data was missing the 'Placebo' treatment.

image

We could probably re-write `varN_fctr_reorder()` to maintain old factor levels... However, I'm not sure we have to... we'd have to do some digging to inspect each time it's used to assess if it's appropriate.

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK Are you done working on this PR? 'Asking because you pushed a handful of commits after asking for my review.

Yes, I'm all done! Just thought I'd knock out an easy fix for #108.

**Pull request merged**
